# Generated by Django 4.2.4 on 2023-09-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveIntegerField()),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Primary_Group',
            fields=[
                ('primary_group_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('primary_group_name', models.CharField(max_length=255)),
                ('primary_group_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_number', models.PositiveIntegerField()),
                ('ledger_name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.group')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('voucherNo', models.IntegerField()),
                ('voucherCode', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('narration', models.CharField(blank=True, max_length=255, null=True)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ledger')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.primary_group')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='primary_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.primary_group'),
        ),
    ]
