# Generated by Django 4.2.4 on 2023-10-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='group',
            new_name='c_group',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='ledger',
            new_name='c_ledger',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='primary_group',
            new_name='c_primary_group',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='receipt',
            name='d_group',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='d_ledger',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='d_primary_group',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='reference',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
