# Generated by Django 4.2.4 on 2023-09-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentries',
            old_name='subcategory',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='journalentries',
            old_name='account',
            new_name='ledger',
        ),
        migrations.RenameField(
            model_name='journalentries',
            old_name='category',
            new_name='primary_group',
        ),
    ]
