# Generated by Django 4.2.4 on 2023-10-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_rename_group_receipt_c_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='transaction_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
