# Generated by Django 4.2.4 on 2023-09-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_journalentries_id_journalentries_vouchercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentries',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
