# Generated by Django 4.2.4 on 2023-09-19 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_rename_subcategory_journalentries_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentries',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentries',
            name='invoice_no',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
