# Generated by Django 4.2.4 on 2023-09-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journalentries_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentries',
            old_name='śubcategory',
            new_name='subcategory',
        ),
    ]
