# Generated by Django 4.2.4 on 2023-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_receipt_transaction_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='group',
            new_name='c_group',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='ledger',
            new_name='c_ledger',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='primary_group',
            new_name='c_primary_group',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='credit',
            new_name='debit',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='receipt_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='d_group',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='d_ledger',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='d_primary_group',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
