# Generated by Django 4.2.4 on 2023-09-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_śubcategory_journalentries_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentries',
            name='voucherNo',
            field=models.IntegerField(),
        ),
    ]
