# Generated by Django 4.2.4 on 2023-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_group_payment_c_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreceipt',
            name='final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='taxed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
