# Generated by Django 4.2.4 on 2023-11-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_salesreceipt_final_salesreceipt_taxed'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreceipt',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='untPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
