# Generated by Django 4.2.4 on 2023-09-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_journalentries_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentries',
            name='narration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
