# Generated by Django 4.2.4 on 2023-09-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_journalentries_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentries',
            name='narration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
